### ISSUE TITLE
Reconnect to imap when connection fails

### ISSUE THREAD

**Issue by gramakri** [cloudron-io/guacamoly#16]
Looks like it does not reconnect to IMAP after a failure. Restarting the app did the trick.

```
Aug 13 21:21:36 girish.in docker[2589]: ERROR Janitor IMAP error: getaddrinfo ENOTFOUND mail mail:9993 [ /app/code/src/mail.js:204:17 ] 
Aug 13 21:21:36 girish.in docker[2589]: stack: 
Aug 13 21:21:36 girish.in docker[2589]:   """
Aug 13 21:21:36 girish.in docker[2589]:     Error: getaddrinfo ENOTFOUND mail mail:9993
Aug 13 21:21:36 girish.in docker[2589]:         at errnoException (dns.js:26:10)
Aug 13 21:21:36 girish.in docker[2589]:         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
Aug 13 21:21:36 girish.in docker[2589]:   """
Aug 13 21:21:36 girish.in docker[2589]: message:  getaddrinfo ENOTFOUND mail mail:9993
Aug 13 21:21:36 girish.in docker[2589]: code:     ENOTFOUND
Aug 13 21:21:36 girish.in docker[2589]: errno:    ENOTFOUND
Aug 13 21:21:36 girish.in docker[2589]: syscall:  getaddrinfo
Aug 13 21:21:36 girish.in docker[2589]: hostname: mail
Aug 13 21:21:36 girish.in docker[2589]: host:     mail
Aug 13 21:21:36 girish.in docker[2589]: port:     9993
Aug 13 21:21:36 girish.in docker[2589]: source:   socket
Aug 13 21:21:36 girish.in docker[2589]: ERROR IMAP error: getaddrinfo ENOTFOUND mail mail:9993 [ /app/code/src/mail.js:145:17 ] 
Aug 13 21:21:36 girish.in docker[2589]: stack: 
Aug 13 21:21:36 girish.in docker[2589]:   """
Aug 13 21:21:36 girish.in docker[2589]:     Error: getaddrinfo ENOTFOUND mail mail:9993
Aug 13 21:21:36 girish.in docker[2589]:         at errnoException (dns.js:26:10)
Aug 13 21:21:36 girish.in docker[2589]:         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
Aug 13 21:21:36 girish.in docker[2589]:   """
Aug 13 21:21:36 girish.in docker[2589]: message:  getaddrinfo ENOTFOUND mail mail:9993
Aug 13 21:21:36 girish.in docker[2589]: code:     ENOTFOUND
Aug 13 21:21:36 girish.in docker[2589]: errno:    ENOTFOUND
Aug 13 21:21:36 girish.in docker[2589]: syscall:  getaddrinfo
Aug 13 21:21:36 girish.in docker[2589]: hostname: mail
Aug 13 21:21:36 girish.in docker[2589]: host:     mail
Aug 13 21:21:36 girish.in docker[2589]: port:     9993
Aug 13 21:21:36 girish.in docker[2589]: source:   socket
```

**Comment by nebulade** [comment]
After testing this, it does reconnect fine after showing those errors. It reconnects with every run over the mailbox, which happens ever minute currently. 

Please reopen if that was not the case.
